# Generated by Django 4.2.2 on 2023-06-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'PROFESOR', 'verbose_name_plural': 'PROFESORES'},
        ),
    ]
