# Generated by Django 4.2.2 on 2023-06-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teachers_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='address_teacher',
            field=models.CharField(max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='age_teacher',
            field=models.IntegerField(null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='email_teacher',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='id_teacher',
            field=models.IntegerField(null=True, unique=True, verbose_name='Número de identificación'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='last_name_teacher',
            field=models.CharField(max_length=20, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='name_teacher',
            field=models.CharField(max_length=20, null=True, verbose_name='Nombre'),
        ),
    ]
