# Generated by Django 4.2.2 on 2023-06-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'ESTUDIANTE', 'verbose_name_plural': 'ESTUDIANTES'},
        ),
    ]
