# Generated by Django 4.2.2 on 2023-06-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_students_id_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id_student',
            field=models.IntegerField(null=True, unique=True, verbose_name='Número de identificación'),
        ),
    ]
