# Generated by Django 4.2.2 on 2023-06-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_students_id_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='address_student',
            field=models.CharField(max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='students',
            name='age_student',
            field=models.IntegerField(null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='students',
            name='email_student',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name_student',
            field=models.CharField(max_length=20, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name_student',
            field=models.CharField(max_length=20, null=True, verbose_name='Nombre'),
        ),
    ]
