# Generated by Django 4.2.2 on 2023-06-17 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '__first__'),
        ('teachers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_course', models.IntegerField(null=True, unique=True)),
                ('name_course', models.CharField(max_length=50, null=True)),
                ('description_course', models.TextField(null=True)),
                ('cources_students', models.ManyToManyField(null=True, to='students.students')),
                ('course_teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers')),
            ],
        ),
    ]
