# Generated by Django 4.2.2 on 2023-06-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_cources_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'CURSO', 'verbose_name_plural': 'CURSOS'},
        ),
    ]
