# Generated by Django 4.2.2 on 2023-06-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teachers_address_teacher_and_more'),
        ('students', '0005_alter_students_address_student_and_more'),
        ('courses', '0003_alter_courses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cources_students',
            field=models.ManyToManyField(to='students.students', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers', verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description_course',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='id_course',
            field=models.IntegerField(null=True, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name_course',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre'),
        ),
    ]
